/**
 * One-off generator: transcribes the Phase 1 mock fixtures into SQL INSERT
 * statements so the real Supabase catalog launches with the same rich
 * content (photography, copy, host/review relationships) instead of an
 * empty database. Not part of the app bundle — run with `npx tsx
 * scripts/generate-seed.ts > supabase/seed.sql`.
 */
import { listingsMock } from "../src/lib/data/mock/listings.mock";
import { destinationsMock } from "../src/lib/data/mock/destinations.mock";
import { hostsMock } from "../src/lib/data/mock/hosts.mock";
import { reviewsMock } from "../src/lib/data/mock/reviews.mock";
import { testimonialsMock } from "../src/lib/data/mock/testimonials.mock";
import { faqsMock } from "../src/lib/data/mock/faqs.mock";
import { AMENITIES } from "../src/lib/constants";

function sqlStr(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNum(value: number | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return String(value);
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

function sqlTextArray(values: readonly string[]): string {
  if (values.length === 0) return "'{}'::text[]";
  return `ARRAY[${values.map((v) => sqlStr(v)).join(", ")}]::text[]`;
}

function sqlJsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts from src/lib/data/mock/*.mock.ts",
  "-- Run after all migrations in supabase/migrations/ have been applied.",
  "",
];

lines.push("-- Hosts");
for (const h of hostsMock) {
  lines.push(
    `insert into hosts (id, name, avatar_url, response_rate, response_time, joined_year, bio) values (` +
      [
        sqlStr(h.id),
        sqlStr(h.name),
        sqlStr(h.avatarUrl),
        sqlNum(h.responseRate),
        sqlStr(h.responseTime),
        sqlNum(h.joinedYear),
        sqlStr(h.bio),
      ].join(", ") +
      ");"
  );
}

lines.push("", "-- Destinations");
for (const d of destinationsMock) {
  lines.push(
    `insert into destinations (id, slug, name, country, image_url, listing_count, blurb) values (` +
      [
        sqlStr(d.id),
        sqlStr(d.slug),
        sqlStr(d.name),
        sqlStr(d.country),
        sqlStr(d.imageUrl),
        sqlNum(d.listingCount),
        sqlStr(d.blurb),
      ].join(", ") +
      ");"
  );
}

lines.push("", "-- Amenities (static reference set)");
for (const a of AMENITIES) {
  lines.push(
    `insert into amenities (id, label, icon) values (${sqlStr(a.id)}, ${sqlStr(a.label)}, ${sqlStr(a.icon)});`
  );
}

lines.push("", "-- Listings");
for (const l of listingsMock) {
  lines.push(
    `insert into listings (
      id, slug, title, destination_id, city, country, neighborhood, lat, lng,
      images, price_amount, price_currency, weekend_price_amount, weekend_price_currency,
      cleaning_fee_amount, cleaning_fee_currency, max_guests, bedrooms, bathrooms,
      square_meters, amenity_ids, luxury_score, is_instant_book, is_featured,
      is_pet_friendly, has_pool, has_wifi, has_parking, has_sea_view,
      short_description, description, house_rules, check_in_time, check_out_time,
      host_id, rating, review_count, nearby_attractions, created_at
    ) values (` +
      [
        sqlStr(l.id),
        sqlStr(l.slug),
        sqlStr(l.title),
        sqlStr(l.destinationId),
        sqlStr(l.city),
        sqlStr(l.country),
        sqlStr(l.neighborhood),
        sqlNum(l.location.lat),
        sqlNum(l.location.lng),
        sqlTextArray(l.images),
        sqlNum(l.pricePerNight.amount),
        sqlStr(l.pricePerNight.currency),
        sqlNum(l.weekendPricePerNight?.amount),
        sqlStr(l.weekendPricePerNight?.currency),
        sqlNum(l.cleaningFee.amount),
        sqlStr(l.cleaningFee.currency),
        sqlNum(l.maxGuests),
        sqlNum(l.bedrooms),
        sqlNum(l.bathrooms),
        sqlNum(l.squareMeters),
        sqlTextArray(l.amenityIds),
        sqlNum(l.luxuryScore),
        sqlBool(l.isInstantBook),
        sqlBool(l.isFeatured),
        sqlBool(l.isPetFriendly),
        sqlBool(l.hasPool),
        sqlBool(l.hasWifi),
        sqlBool(l.hasParking),
        sqlBool(l.hasSeaView),
        sqlStr(l.shortDescription),
        sqlStr(l.description),
        sqlTextArray(l.houseRules),
        sqlStr(l.checkInTime),
        sqlStr(l.checkOutTime),
        sqlStr(l.hostId),
        sqlNum(l.rating),
        sqlNum(l.reviewCount),
        sqlJsonb(l.nearbyAttractions),
        sqlStr(l.createdAt),
      ].join(", ") +
      ");"
  );
}

lines.push("", "-- Reviews");
for (const r of reviewsMock) {
  lines.push(
    `insert into reviews (id, listing_id, author_name, author_avatar_url, rating, comment, date) values (` +
      [
        sqlStr(r.id),
        sqlStr(r.listingId),
        sqlStr(r.authorName),
        sqlStr(r.authorAvatarUrl),
        sqlNum(r.rating),
        sqlStr(r.comment),
        sqlStr(r.date),
      ].join(", ") +
      ");"
  );
}

lines.push("", "-- Testimonials");
for (const t of testimonialsMock) {
  lines.push(
    `insert into testimonials (id, author_name, author_location, avatar_url, quote, rating) values (` +
      [
        sqlStr(t.id),
        sqlStr(t.authorName),
        sqlStr(t.authorLocation),
        sqlStr(t.avatarUrl),
        sqlStr(t.quote),
        sqlNum(t.rating),
      ].join(", ") +
      ");"
  );
}

lines.push("", "-- FAQs");
faqsMock.forEach((f, index) => {
  lines.push(
    `insert into faqs (id, question, answer, sort_order) values (${sqlStr(f.id)}, ${sqlStr(f.question)}, ${sqlStr(f.answer)}, ${index});`
  );
});

console.log(lines.join("\n"));
